In [5]:
import pandas as pd

from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import seaborn as sns

# Load the CSV file into a DataFrame
data = pd.read_csv('../../data/surface_temperature/average-monthly-surface-temperature.csv')

# Display basic information about the DataFrame
data.info()

# Display summary statistics for numerical columns
data.describe()

# Display the number of missing values in each column
data.isnull().sum()

# Display the unique values in each column
for column in data.columns:
    print(f"{column}: {data[column].unique()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 6 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Entity                         198900 non-null  object
 1   Code                           198900 non-null  object
 2   year                           198900 non-null  int64
 3   Day                            198900 non-null  object
 4   Average surface temperature    198900 non-null  float64
 5   Average surface temperature.1  198900 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 9.1+ MB
Entity: ['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia'
 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi'
 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba'
 'Cyprus' 'Czechia' 'Democratic Republic of Congo' 'Denmark' 'Djibouti'
 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Falkland Islands' 'Faroe Islands' 'Fiji' 'Finland' 'France'
 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece'
 'Greenland' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Heard Island and McDonald Islands' 'Honduras' 'Hong Kong' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man'
 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg' 'Madagascar'
 'Malawi' 'Malaysia' 'Mali' 'Mauritania' 'Mauritius' 'Mexico' 'Moldova'
 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Korea' 'North Macedonia' 'Norway' 'Oman' 'Pakistan'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Helena' 'Saint Vincent and the Grenadines' 'Samoa'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia'
 'South Africa' 'South Georgia and the South Sandwich Islands'
 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname'
 'Sweden' 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'World' 'Yemen' 'Zambia' 'Zimbabwe']
Code: ['AFG' 'ALB' 'DZA' 'ASM' 'AND' 'AGO' 'AIA' 'ATG' 'ARG' 'ARM' 'AUS' 'AUT'
 'AZE' 'BHS' 'BHR' 'BGD' 'BLR' 'BEL' 'BLZ' 'BEN' 'BTN' 'BOL' 'BIH' 'BWA'
 'BRA' 'BRN' 'BGR' 'BFA' 'BDI' 'KHM' 'CMR' 'CAN' 'CPV' 'CYM' 'CAF' 'TCD'
 'CHL' 'CHN' 'COL' 'COM' 'COG' 'COK' 'CRI' 'CIV' 'HRV' 'CUB' 'CYP' 'CZE'
 'COD' 'DNK' 'DJI' 'DOM' 'TLS' 'ECU' 'EGY' 'SLV' 'GNQ' 'ERI' 'EST' 'SWZ'
 'ETH' 'FLK' 'FRO' 'FJI' 'FIN' 'FRA' 'PYF' 'GAB' 'GMB' 'GEO' 'DEU' 'GHA'
 'GRC' 'GRL' 'GTM' 'GIN' 'GNB' 'GUY' 'HTI' 'HMD' 'HND' 'HKG' 'HUN' 'ISL'
 'IND' 'IDN' 'IRN' 'IRQ' 'IRL' 'IMN' 'ISR' 'ITA' 'JAM' 'JPN' 'JOR' 'KAZ'
 'KEN' 'KIR' 'OWID_KOS' 'KWT' 'KGZ' 'LAO' 'LVA' 'LBN' 'LSO' 'LBR' 'LBY'
 'LTU' 'LUX' 'MDG' 'MWI' 'MYS' 'MLI' 'MRT' 'MUS' 'MEX' 'MDA' 'MNG' 'MNE'
 'MAR' 'MOZ' 'MMR' 'NAM' 'NPL' 'NLD' 'NCL' 'NZL' 'NIC' 'NER' 'NGA' 'PRK'
 'MKD' 'NOR' 'OMN' 'PAK' 'PSE' 'PAN' 'PNG' 'PRY' 'PER' 'PHL' 'POL' 'PRT'
 'PRI' 'QAT' 'ROU' 'RUS' 'RWA' 'SHN' 'VCT' 'WSM' 'STP' 'SAU' 'SEN' 'SRB'
 'SYC' 'SLE' 'SVK' 'SVN' 'SLB' 'SOM' 'ZAF' 'SGS' 'KOR' 'SSD' 'ESP' 'LKA'
 'SDN' 'SUR' 'SWE' 'CHE' 'SYR' 'TJK' 'TZA' 'THA' 'TGO' 'TTO' 'TUN' 'TUR'
 'TKM' 'UGA' 'UKR' 'ARE' 'GBR' 'USA' 'VIR' 'URY' 'UZB' 'VUT' 'VEN' 'VNM'
 'OWID_WRL' 'YEM' 'ZMB' 'ZWE']
year: [1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953
 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967
 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981
 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995
 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009
 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023
 2024]
Day: ['1940-01-15' '1940-02-15' '1940-03-15' ... '2024-10-15' '2024-11-15'
 '2024-12-15']
Average surface temperature: [-2.0324936  -0.73350304  1.999134   ... 23.642931   24.40703
 25.672321  ]
Average surface temperature.1: [11.327695 13.324756 12.885448 ... 21.591951 22.349144 22.92125 ]

In [12]:
# Drop rows with missing values
data = data.dropna()

# Drop the features that are to be ignored
data = data.drop(['Entity', 'Code', 'Day'], axis=1)

# Encode categorical variables (if any)
# No categorical variables to encode in this dataset

# Separate the features and the target variable
features = data.drop(['Average surface temperature'], axis=1)
targets = data['Average surface temperature']

# Split the data into training and testing sets
features_train, features_test, targets_train, targets_test = train_test_split(features, targets, test_size=0.2, random_state=42)

# Initialize the LazyClassifier with default hyperparameters
lazyClassifier = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)

# Fit the LazyClassifier on the training data and get the models and predictions
models, predictions = lazyClassifier.fit(features_train, features_test, targets_train, targets_test)
models

100%|██████████| 32/32 [00:00<00:00, 34.66it/s]

Empty DataFrame
Columns: [Accuracy, Balanced Accuracy, ROC AUC, F1 Score, Time Taken]
Index: []